jwt:
  secret: 'a8a845f3-29ea-4844-8a8e-5a153da9f6e2a8a845f3-29ea-4844-8a8e-5a153da9f6e2'

server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/supportportal
    password:
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
